version: '3.8'

services:
  client:
    build: ./client
    image: zatti/feirinha-client
    container_name: feirinha-client
    volumes:
      - ./client/:/usr/src/client
      - /usr/src/client/node_modules
      - /usr/src/client/.next
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - server
  server:
    build: ./server
    image: zatti/feirinha-server
    container_name: feirinha-server
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./server/:/usr/src/server/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    container_name: feirinha-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=rootroot
      - POSTGRES_DB=feirinhagti

volumes:
  postgres_data: