# Generated by Django 4.0.4 on 2022-05-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feirante',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='matricula',
            field=models.IntegerField(unique=True),
        ),
    ]
