# Generated by Django 4.0.4 on 2022-05-16 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_saldo_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='date',
            new_name='data_compra',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='user_id',
            new_name='user',
        ),
    ]
