# Generated by Django 4.0.4 on 2022-05-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_date_history_data_compra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='matricula',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
